/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tier = IDL.Variant({
  'HT1' : IDL.Null,
  'HT2' : IDL.Null,
  'HT3' : IDL.Null,
  'HT4' : IDL.Null,
  'HT5' : IDL.Null,
  'LT1' : IDL.Null,
  'LT2' : IDL.Null,
  'LT3' : IDL.Null,
  'LT4' : IDL.Null,
  'LT5' : IDL.Null,
});
export const Category = IDL.Variant({
  'Axe' : IDL.Null,
  'SMP' : IDL.Null,
  'UHC' : IDL.Null,
  'Sword' : IDL.Null,
  'Mace' : IDL.Null,
  'Crystal' : IDL.Null,
  'Spearmace' : IDL.Null,
  'DiamondSMP' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tier' : Tier,
  'score' : IDL.Int,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'category' : Category,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func(
      [IDL.Text, Tier, IDL.Int, Category, IDL.Opt(IDL.Text)],
      [Player],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayersByCategory' : IDL.Func([Category], [IDL.Vec(Player)], ['query']),
  'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
  'getPlayersByTierAndCategory' : IDL.Func(
      [Tier, Category],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePlayer' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPlayersByName' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tier = IDL.Variant({
    'HT1' : IDL.Null,
    'HT2' : IDL.Null,
    'HT3' : IDL.Null,
    'HT4' : IDL.Null,
    'HT5' : IDL.Null,
    'LT1' : IDL.Null,
    'LT2' : IDL.Null,
    'LT3' : IDL.Null,
    'LT4' : IDL.Null,
    'LT5' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Axe' : IDL.Null,
    'SMP' : IDL.Null,
    'UHC' : IDL.Null,
    'Sword' : IDL.Null,
    'Mace' : IDL.Null,
    'Crystal' : IDL.Null,
    'Spearmace' : IDL.Null,
    'DiamondSMP' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tier' : Tier,
    'score' : IDL.Int,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'category' : Category,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [IDL.Text, Tier, IDL.Int, Category, IDL.Opt(IDL.Text)],
        [Player],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayersByCategory' : IDL.Func([Category], [IDL.Vec(Player)], ['query']),
    'getPlayersByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
    'getPlayersByTierAndCategory' : IDL.Func(
        [Tier, Category],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePlayer' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPlayersByName' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };