/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Axe' : null } |
  { 'SMP' : null } |
  { 'UHC' : null } |
  { 'Sword' : null } |
  { 'Mace' : null } |
  { 'Crystal' : null } |
  { 'Spearmace' : null } |
  { 'DiamondSMP' : null };
export interface Player {
  'id' : bigint,
  'name' : string,
  'tier' : Tier,
  'score' : bigint,
  'category' : Category,
}
export type Tier = { 'HT1' : null } |
  { 'HT2' : null } |
  { 'HT3' : null } |
  { 'HT4' : null } |
  { 'HT5' : null } |
  { 'LT1' : null } |
  { 'LT2' : null } |
  { 'LT3' : null } |
  { 'LT4' : null } |
  { 'LT5' : null };
export interface _SERVICE {
  'addPlayer' : ActorMethod<[string, Tier, bigint, Category], Player>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getPlayersByCategory' : ActorMethod<[Category], Array<Player>>,
  'getPlayersByTier' : ActorMethod<[Tier], Array<Player>>,
  'getPlayersByTierAndCategory' : ActorMethod<[Tier, Category], Array<Player>>,
  'searchPlayersByName' : ActorMethod<[string], Array<Player>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];