/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Axe' : null } |
  { 'SMP' : null } |
  { 'UHC' : null } |
  { 'Sword' : null } |
  { 'Mace' : null } |
  { 'Crystal' : null } |
  { 'Spearmace' : null } |
  { 'DiamondSMP' : null };
export interface Player {
  'id' : bigint,
  'name' : string,
  'tier' : Tier,
  'score' : bigint,
  'avatarUrl' : [] | [string],
  'category' : Category,
}
export type Tier = { 'HT1' : null } |
  { 'HT2' : null } |
  { 'HT3' : null } |
  { 'HT4' : null } |
  { 'HT5' : null } |
  { 'LT1' : null } |
  { 'LT2' : null } |
  { 'LT3' : null } |
  { 'LT4' : null } |
  { 'LT5' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<
    [string, Tier, bigint, Category, [] | [string]],
    Player
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayersByCategory' : ActorMethod<[Category], Array<Player>>,
  'getPlayersByTier' : ActorMethod<[Tier], Array<Player>>,
  'getPlayersByTierAndCategory' : ActorMethod<[Tier, Category], Array<Player>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePlayer' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPlayersByName' : ActorMethod<[string], Array<Player>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];